/bt_navigator:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    action_server_result_timeout: 900.0
    always_reload_bt_xml: false
    autostart_node: false
    bond_heartbeat_period: 0.1
    bt_loop_duration: 10
    default_nav_through_poses_bt_xml: /home/boris/ros2_ws/install/nav2_bt_navigator/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
    default_nav_to_pose_bt_xml: /home/boris/ros2_ws/install/nav2_bt_navigator/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    default_server_timeout: 20
    error_code_names:
    - compute_path_error_code
    - follow_path_error_code
    global_frame: map
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    navigate_through_poses:
      enable_groot_monitoring: false
      groot_server_port: 1669
      plugin: nav2_bt_navigator::NavigateThroughPosesNavigator
    navigate_to_pose:
      enable_groot_monitoring: false
      groot_server_port: 1667
      plugin: nav2_bt_navigator::NavigateToPoseNavigator
    navigators:
    - navigate_to_pose
    - navigate_through_poses
    odom_topic: /odom
    path_blackboard_id: path
    plugin_lib_names: []
    qos_overrides:
      /tf:
        subscription:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        subscription:
          depth: 100
          history: keep_last
          reliability: reliable
    robot_base_frame: base_link
    start_type_description_service: true
    transform_tolerance: 0.1
    use_sim_time: false
    wait_for_service_timeout: 1000

