/controller_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    FollowPath:
      ConstraintCritic:
        cost_power: 1
        cost_weight: 4.0
        enabled: true
      CostCritic:
        collision_cost: 1000000.0
        consider_footprint: false
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        enabled: true
        inflation_layer_name: ''
        near_collision_cost: 253
        near_goal_distance: 1.0
        trajectory_point_step: 2
      GoalAngleCritic:
        cost_power: 1
        cost_weight: 3.0
        enabled: true
        threshold_to_consider: 0.5
      GoalCritic:
        cost_power: 1
        cost_weight: 5.0
        enabled: true
        threshold_to_consider: 1.4
      PathAlignCritic:
        cost_power: 1
        cost_weight: 14.0
        enabled: true
        max_path_occupancy_ratio: 0.05
        offset_from_furthest: 20
        threshold_to_consider: 0.5
        trajectory_point_step: 4
        use_path_orientations: false
      PathAngleCritic:
        cost_power: 1
        cost_weight: 2.0
        enabled: true
        max_angle_to_furthest: 1.0
        mode: 0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
      PathFollowCritic:
        cost_power: 1
        cost_weight: 5.0
        enabled: true
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PreferForwardCritic:
        cost_power: 1
        cost_weight: 5.0
        enabled: true
        threshold_to_consider: 0.5
      TrajectoryVisualizer:
        time_step: 3
        trajectory_step: 5
      ax_max: 3.0
      ax_min: -3.0
      ay_max: 3.0
      ay_min: -3.0
      az_max: 3.5
      batch_size: 2000
      critics:
      - ConstraintCritic
      - CostCritic
      - GoalCritic
      - GoalAngleCritic
      - PathAlignCritic
      - PathFollowCritic
      - PathAngleCritic
      - PreferForwardCritic
      enforce_path_inversion: false
      gamma: 0.015
      iteration_count: 1
      max_robot_pose_search_dist: 1.5
      model_dt: 0.05
      motion_model: DiffDrive
      plugin: nav2_mppi_controller::MPPIController
      prune_distance: 1.7
      regenerate_noises: true
      retry_attempt_limit: 1
      temperature: 0.3
      time_steps: 56
      transform_tolerance: 1.0
      visualize: false
      vx_max: 0.6
      vx_min: -0.6
      vx_std: 0.2
      vy_max: 0.0
      vy_std: 0.2
      wz_max: 1.2
      wz_std: 0.4
    action_server_result_timeout: 10.0
    autostart_node: false
    bond_heartbeat_period: 0.1
    controller_frequency: 20.0
    controller_plugins:
    - FollowPath
    controller_server:
      verbose: false
    costmap_update_timeout: 0.3
    enable_stamped_cmd_vel: false
    failure_tolerance: 0.3
    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    goal_checker_plugins:
    - general_goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    odom_topic: odom
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
    progress_checker_plugins:
    - progress_checker
    publish_zero_velocity: true
    speed_limit_topic: speed_limit
    start_type_description_service: true
    use_realtime_priority: false
    use_sim_time: false

