/planner_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    GridBased:
      allow_unknown: true
      plugin: nav2_navfn_planner::NavfnPlanner
      tolerance: 0.5
      use_astar: false
      use_final_approach_orientation: false
    action_server_result_timeout: 10.0
    autostart_node: false
    bond_heartbeat_period: 0.1
    costmap_update_timeout: 1.0
    expected_planner_frequency: 20.0
    planner_plugins:
    - GridBased
    start_type_description_service: true
    use_sim_time: false

